version: '3.1'

services:
  app:
    build: .
    container_name: tasks-service
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - database
    networks:
      - tasks-network
  database:
    image: postgres
    container_name: tasks-database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks
    ports:
      - 5432:5432
    networks:
      - tasks-network

networks:
  tasks-network:
    driver: bridge

